name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.4.5
  - pandas=1.4.3
  - pandas-profiling=3.2.0
  - ipywidgets=8.0.1
  - pip=22.2.2
  - pyarrow=9.0.0
  - seaborn=0.11.2
  - pip:
      - wandb