name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - cookiecutter=2.1.1
  - git=2.37.2
  - hydra-core=1.2.0
  - ipython=8.4.0
  - jupyterlab=3.4.5
  - mamba=0.25.0
  - matplotlib=3.5.3
  - mlflow=1.28.0
  - notebook=6.4.12
  - pandas=1.4.3
  - pip=22.2.2
  - pip:
      - wandb
